server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location = /taro { try_files /taro.html /index.html; }
    location = /matrica { try_files /matrica.html /index.html; }
    location = /sovmestimost { try_files /sovmestimost.html /index.html; }
    location /r/ {
        if ($request_method = POST) {
            return 303 $scheme://$host$request_uri;
        }
        try_files /index.html =404;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
