server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location = /taro { try_files /taro.html /index.html; }
    location = /matrica { try_files /matrica.html /index.html; }
    location = /sovmestimost { try_files /sovmestimost.html /index.html; }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
